name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  checks: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/328218260604/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-action-sa@amz-seller-hub.iam.gserviceaccount.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
        run: |
          cd frontend
          npm run build

      - name: Install dependencies (Functions)
        run: |
          cd functions
          pip install -r requirements.txt

      - name: Deploy to Firebase
        uses: firebase/firebase-tools-action@v0
        with:
          args: deploy --only hosting,functions
        env:
          PROJECT_ID: amz-seller-hub
